jobs:
  - name: management-dev
    max_in_flight: 1
    plan:
      - get: docker-create-metrics-data-batch
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
      - .: (( inject meta.plan.terraform-plan ))
