resources:
  - name: dwpdigital-docker-create-metrics-data-batch
    type: registry-image-resource
    source:
      repository: dwpdigital/docker-create-metrics-data-batch
    check_every: 5m

  - name: ecr-dwpdigital-docker-create-metrics-data-batch-dev
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "docker-create-metrics-data-batch"

  - name: ecr-dwpdigital-docker-create-metrics-data-batch
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "docker-create-metrics-data-batch"
      aws_role_arn: arn:aws:iam::((dataworks.aws_management_acc)):role/ci

jobs:
  - name: mirror-dwpdigital-docker-create-metrics-data-batch-dev
    serial_groups: [docker-create-metrics-data-batch]
    plan:
      - get: dwpdigital-docker-create-metrics-data-batch
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-docker-create-metrics-data-batch-dev
        params:
          image: "dwpdigital-docker-create-metrics-data-batch/image.tar"
        attempts: 3

  - name: mirror-dwpdigital-docker-create-metrics-data-batch
    serial_groups: [docker-create-metrics-data-batch]
    plan:
      - get: dwpdigital-docker-create-metrics-data-batch
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-docker-create-metrics-data-batch
        params:
          image: "dwpdigital-docker-create-metrics-data-batch/image.tar"
        attempts: 3
